export const INJECTION_TOKENS = {
  DEFAULT_DTO: 'DEFAULT_DTO',
  DEFAULT_SUCCESS_CODE: 'DEFAULT_SUCCESS_CODE',
  DEFAULT_ERROR_CODE: 'DEFAULT_ERROR_CODE',
  REDIS_SERVICE: 'IRedisService',
  AUTH_COMMAND_SERVICE: 'IAuthCommandService',
} as const;
